
#define PANDA_MAJOR_VERSION 1
#define PANDA_MINOR_VERSION 9
#define PANDA_SEQUENCE_VERSION 0
#define PANDA_VERSION 1008999
#define PANDA_NUMERIC_VERSION 1008999
#define PANDA_VERSION_STR "1.9.0"
#define PANDA_ABI_VERSION_STR "1.9"
#define PANDA_DISTRIBUTOR "astron"
#define PANDA_PACKAGE_VERSION_STR "dev"
#define PANDA_PACKAGE_HOST_URL "https://runtime.panda3d.org/"

#undef  PANDA_OFFICIAL_VERSION
